name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_IMAGE_REPOSITORY: zerosuxx/gh-actions-cache-test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zerosuxx
          password: ${{ secrets.DH_TOKEN }}

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: packed
          push: true
          tags: |
            ${{ env.APP_IMAGE_REPOSITORY }}:${{ steps.short-sha.outputs.sha }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: type=registry,ref=${{ env.APP_IMAGE_REPOSITORY }}:buildcache
          cache-to: type=inline,mode=max
          #cache-to: type=registry,ref=${{ env.APP_IMAGE_REPOSITORY }}:buildcache,mode=max
